staticPublishPath: .
headers:
  - path: "/*.fset"
    name: "Content-Type"
    value: "application/octet-stream"
  - path: "/*.fset3"
    name: "Content-Type"
    value: "application/octet-stream"
  - path: "/*.iset"
    name: "Content-Type"
    value: "application/octet-stream"
  - path: "/*.fset"
    name: "Cache-Control"
    value: "no-transform"
  - path: "/*.fset3"
    name: "Cache-Control"
    value: "no-transform"
  - path: "/*.iset"
    name: "Cache-Control"
    value: "no-transform"
gzip: false
